version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - transcendence-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - transcendence-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - backend-data:/app
    networks:
      - transcendence-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend-data:/app
    networks:
      - transcendence-network

networks:
  transcendence-network:

volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BACKEND_VOLUME}

  frontend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${FRONTEND_VOLUME}

  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
