version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - transcendence-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - transcendence-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app
    networks:
      - transcendence-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend-data:/app
    networks:
      - transcendence-network

networks:
  transcendence-network:

volumes:
  backend-data:
    name: backend-data
    driver: local
    driver_opts:
      type: none
      #device: ./backend
      device: /home/fbelthoi/ft_transcendence/backend
      o: bind

  frontend-data:
    name: frontend-data
    driver: local
    driver_opts:
      type: none
      #device: ./frontend
      device: /home/fbelthoi/ft_transcendence/frontend
      o: bind